// <auto-generated/>
global using global::BLL;
global using global::DryIoc;
global using global::DryIoc.Microsoft.DependencyInjection;
global using global::DryIoc.WebApi;
global using global::Microsoft.AspNetCore.Builder;
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.Extensions.Hosting;
global using global::Microsoft.OpenApi.Models;
global using global::Service.API;
global using global::System.IO;
global using global::System.Reflection;

